remote_theme: daattali/beautiful-jekyll@master
plugins:
  - jekyll-remote-theme

title: Road Sign Classifier
description: An image classifier that recognizes different types of road signs from images using deep learning.

# Navigation Links 
navbar-links:
  Home: "https://mohtasim22.github.io/Road-Sign-Classifier/"
  Road Sign Classifier: "road_sign_classifier.html"

sass:
  style: compressed